{{- if and .Values.tls.enabled .Values.tls.createCertificate }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "logarys-documentation.fullname" . }}
  labels:
    {{- include "logarys-documentation.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.tls.revisionHistoryLimit }}
  privateKey:
    rotationPolicy: {{ .Values.tls.privateKeyRotationPolicy }}
  secretName: {{ .Values.tls.secretName }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.tls.clusterIssuer }}
  dnsNames:
    - {{ .Values.host | quote }}
{{- end }}
