{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  labels:
    {{- include "logarys-documentation.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  duration: {{ .Values.certificate.duration | quote }}
  renewBefore: {{ .Values.certificate.renewBefore | quote }}
  dnsNames:
    - {{ .Values.apisix.host | quote }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: {{ .Values.certificate.issuerRef.kind }}
    group: {{ .Values.certificate.issuerRef.group }}
{{- end }}
